### ISSUE TITLE
[Bug] Web doesn't build

### ISSUE THREAD

**Issue by izmystic** [Legacy-Scripts/LGF_Loading#1]
- Type: Bug Report
- Resource: LGF_Loading
## Bug Report:
1. Reproduction steps
    - building resource

Web doesn't build with the error `[vite]: Rollup failed to resolve import "@config" from "server_directory/LGF_Loading/web/src/App.tsx".`

**Comment by izmystic** [comment]
IDK if its a me issue, but even with 427f6a64ed1e8e559dfc125450bdc0607d710832 & 4b15d65191a3137f5ae953cb009c48b7d3c46bc7 it doesn't build for the same reason

**Comment by Maximus7474** [comment]
We're aware of the issue, it's being looked into. You'll be notified when it's fixed

**Comment by ViskCY** [comment]
Sorry for the long time but pushed a fix to v1.0.1 release also included a build.

**Comment by izmystic** [comment]
fixed with 17b317f9740a7dda77f9c4797e85afe9971f8961
