### ISSUE TITLE
[Bug Report / Feature Request] deferrals.handover is not a function error

### ISSUE THREAD

**Issue by StigmaAU** [Legacy-Scripts/LGF_Loading#2]
- Type: Bug Report / Feature Request
- Resource: LGF_Banking, LGF_Notify, etc...

## Bug Report:
1. Reproduction steps
    - Join the server after first building, server console will throw a deferrals.handover is not a function error meaning that the player will not see their Steam ID in the top left.
![image](https://github.com/user-attachments/assets/197fe07a-688c-484e-89fb-c65c955b2d01)

2. Configuration
    # To fix issue go into server.js in ( [folder name]/dist/server.js ) and change
    ``on("playerConnecting", (name, deferrals)``
    to
    ``on("playerConnecting", (name, _, deferrals)``
    
    having the deferrals in the 3rd parameter fixes the issue, update this in the index.ts as well.
    

## Feature Request / Enhancement:
- Add music player to the bottom right with a volume slider would be cool.

**Comment by ENT510** [comment]
thx, At the time I hadn't tested it yet, if you want you can do a fork

**Comment by Maximus7474** [comment]
Please create a separate issues for bugs and feature requests.
